### ISSUE TITLE
Dépendances

### ISSUE THREAD

**Issue by AntoineTurmel** [Jezza34000/jeedom_weback_plugin#2]
Bonjour, 
j'ai une installation de Jeedom (dernière version) sur Rapsberry Pi, j'essaie d'installer les dépendances mais cela ne fonctionne pas : 

![image](https://user-images.githubusercontent.com/119288/210819775-8d83bbb5-e0eb-467c-91f5-6069ac1f1172.png)

![image](https://user-images.githubusercontent.com/119288/210819946-350839c9-0b4e-48aa-8a4f-85e384bca6a6.png)

**Comment by AntoineTurmel** [comment]
- j'ai recréé le fichier install_apt.sh à la main en copiant collant le contenu, et maintenant c'est vert.
- par contre le démon ne se démarre pas : 
![image](https://user-images.githubusercontent.com/119288/210835048-5df78f83-aec8-4750-9535-31b4975fe10e.png)

Error: importing module jeedom.jeedom

**Comment by AntoineTurmel** [comment]
pi@raspberrypi:/var/www/html/plugins/weback/resources/demond $ python3 --version
Python 3.9.2
pi@raspberrypi:/var/www/html/plugins/weback/resources/demond $ python3 webackd.py 
Error: importing module jeedom.jeedom

**Comment by AntoineTurmel** [comment]
Corrigé en faisant : sudo pip3 install pyudev

**Comment by Jezza34000** [comment]
Ok parfait
