### ISSUE TITLE
Gestion de carte

### ISSUE THREAD

**Issue by AntoineTurmel** [Jezza34000/jeedom_weback_plugin#3]
Depuis fin décembre, l'application WeBack sur Android ne gère plus la carte (plus d'affichage/enregistrement), c'est pour ça que j'ai commencé à regarder les alternatives utilisables.

La planification de zone n'est du coup plus possible. Je me demandais s'il est possible de contourner ça en construisant une carte dans Jeedom en récupérant les coordonnées en direct de l'appareil (si possible via API ?)

**Comment by Jezza34000** [comment]
Hello,
Oui c'est possible actuellement mon plugin reçoit les informations de carte mais ne les interprètes pas.
Je ne travaille plus sur ce plugin car j'ai migrer toute ma domotique sur Home Assistant, j'ai développé un plugin pour Home Assistant et je boss sur celui-ci.

**Comment by AntoineTurmel** [comment]
Merci de ta réponse, juste pour savoir, utilises tu encore l'application Android WeBack ? Il y a des soucis en ce moment sur la carte qui ne s'affiche plus, et je ne sais pas si c'est lié au problème d'API dont tu parles sur ton repo homeassistant_weback_component.

**Comment by Jezza34000** [comment]
Hello,
Non cela n'a rien a voir.
La gestion des cartes marche sur HomeAssistant avec WeBack.

**Comment by AntoineTurmel** [comment]
Ok, top, dans ce cas j'essaierai rapidement, merci !
